//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.Entities.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEV_Menu
    {
        public int MenuItemId { get; set; }
        public string MenuItemName { get; set; }
        public bool IsAdminMenu { get; set; }
        public string MenuURL { get; set; }
        public bool IsActive { get; set; }
    }
}
