//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.Entities.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JuzerWebsiteEntities : DbContext
    {
        public JuzerWebsiteEntities()
            : base("name=JuzerWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEV_Category> DEV_Category { get; set; }
        public virtual DbSet<DEV_Country> DEV_Country { get; set; }
        public virtual DbSet<DEV_Menu> DEV_Menu { get; set; }
        public virtual DbSet<DEV_TypeOfTransaction> DEV_TypeOfTransaction { get; set; }
        public virtual DbSet<MST_UserInfo> MST_UserInfo { get; set; }
        public virtual DbSet<TRN_Expense> TRN_Expense { get; set; }
        public virtual DbSet<TRN_Income> TRN_Income { get; set; }
        public virtual DbSet<TRN_Notes> TRN_Notes { get; set; }
        public virtual DbSet<WebsiteErrorLog> WebsiteErrorLogs { get; set; }
        public virtual DbSet<CustomerContactInfo> CustomerContactInfoes { get; set; }
    
        public virtual ObjectResult<usp_GetExpenseList_Result> usp_GetExpenseList(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetExpenseList_Result>("usp_GetExpenseList", userIdParameter);
        }
    
        public virtual ObjectResult<usp_GetIncomesList_Result> usp_GetIncomesList(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetIncomesList_Result>("usp_GetIncomesList", userIdParameter);
        }
    
        public virtual ObjectResult<usp_GetNotesList_Result> usp_GetNotesList(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetNotesList_Result>("usp_GetNotesList", userIdParameter);
        }
    
        public virtual ObjectResult<string> AskMe(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AskMe", idParameter);
        }
    }
}
