//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.Entities.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_Notes
    {
        public int NoteId { get; set; }
        public string Subject { get; set; }
        public string NoteText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsImportant { get; set; }
    
        public virtual MST_UserInfo MST_UserInfo { get; set; }
    }
}
